### ISSUE TITLE
Rooms not populating in dropdown for creating new Session

### ISSUE THREAD

**Issue by SHBelsky** [wejs/we-plugin-event#33]
When creating a new session, rooms are not populated in the dropdown menu based on rooms that have previously been created. The dropdown menu is empty and has no choices to select, even though I have a room created already.

**Comment by albertosouza** [comment]
Is working here with Firefox and Chrome then i need more information: 

- Any error in browser console or server terminal (log)?
- How are your browser?
- Enable request log: set `enableRequestLog: true` in config/local.js file and see if it are doing requests on search for rooms

**Comment by albertosouza** [comment]
And check if url `/event/:eventId/cfroom?limit=25&responseType=json&name=` will return and room list

**Comment by SHBelsky** [comment]
1. Only error I get is `bootstrap-datetimepicker.js?v=0.3.0:1477 Uncaught TypeError: option altFieldTimeOnly is not recognized!`, but I get that on other pages so I don't think it's related

2. Google Chrome

3. When I do that and look at the console in Chrome, it just lists navigations to pages, and not requests for data. Example:
`Navigated to http://localhost:4000/event/5/admin/cfsession
Navigated to http://localhost:4000/event/5/admin/cfsession/3/delete?redirectTo=/event/5/admin/cfsession
Navigated to http://localhost:4000/event/5/admin/cfsession
Navigated to http://localhost:4000/event/5/admin/cfsession/create?redirectTo=/event/5/admin/cfsession`

Running `/event/:eventId/cfroom?limit=25&responseType=json&name=` does return a JSON of rooms, I get this:

`
{"cfroom":[{"picture":[{"linkPermanent":"/api/v1/image/6","id":6,"label":null,"description":"Bailey Hall","name":"1460575441106_46da4b20-01ad-11e6-a23c-33dacd9a4784.jpg","size":181819,"encoding":"7bit","active":true,"originalname":"BaileyHall-02.jpg","mime":"image/jpeg","extension":null,"width":"880","height":"570","createdAt":"2016-04-13T19:24:01.000Z","updatedAt":"2016-04-13T19:24:01.000Z","creatorId":1,"urls":{"original":"http://localhost:4000/api/v1/image/original/1460575441106_46da4b20-01ad-11e6-a23c-33dacd9a4784.jpg","thumbnail":"http://localhost:4000/api/v1/image/thumbnail/1460575441106_46da4b20-01ad-11e6-a23c-33dacd9a4784.jpg","mini":"http://localhost:4000/api/v1/image/mini/1460575441106_46da4b20-01ad-11e6-a23c-33dacd9a4784.jpg","medium":"http://localhost:4000/api/v1/image/medium/1460575441106_46da4b20-01ad-11e6-a23c-33dacd9a4784.jpg","large":"http://localhost:4000/api/v1/image/large/1460575441106_46da4b20-01ad-11e6-a23c-33dacd9a4784.jpg"}}],"linkPermanent":"/event/2/cfroom","id":2,"eventId":5,"name":"Bailey Hall","about":"Bailey Auditorium","vacancy":1300,"createdAt":"2016-04-13T19:36:06.000Z","updatedAt":"2016-04-13T19:36:06.000Z"}],"meta":{"cfRegistrationCount":0,"cfcontactCount":0,"count":1}}
`

**Comment by SHBelsky** [comment]
Hold on, I just got this error:

`2016-04-14T13:56:30.258Z - warn: Invalid or undefined argument: 2  { name: ':cfroomId', i: 4 } > undefined 1 cfroom.findOne
GET /event/5/cfroom?limit=25&responseType=json&name= 304 82.127 ms - -
Trace: 404 /toom
    at Object.notFoundResponse (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\responses\methods\index.js:228:15)
    at routeNotFound (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\index.js:506:18)
    at Layer.handle [as handle_request] (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:271:10)
    at C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\index.js:375:13
    at Layer.handle [as handle_request] (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\express\lib\router\index.js:271:10)
    at SessionStrategy.strategy.pass (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\passport\lib\middleware\authenticate.js:325:9)
    at C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\passport\lib\strategies\session.js:65:12
    at pass (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\passport\lib\authenticator.js:327:31)`

**Comment by SHBelsky** [comment]
An additional error...But attempting to delete a session from `/event/:eventID/admin/cfsession/5/edit` gives me this error in console:

`Unhandled rejection TypeError: Cannot read property 'title' of null
    at Object.adminCfSessionFindOne (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-plugin-event\lib\setBreadcrumbs.js:358:66)
    at Object.metatagMiddleware [as middleware] (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\breadcrumb.js:24:82)
    at Array.runBreadcrumbMiddleware (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\index.js:45:25)
    at runHookFunctions (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\simple-hooks-callback\lib\index.js:59:15)
    at afterRunHookFN (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\simple-hooks-callback\lib\index.js:66:7)
    at Object.defaultMiddleware [as default] (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\metatag.js:52:7)
    at Object.metatagMiddleware [as middleware] (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\metatag.js:33:46)
    at Array.runMetatagMiddleware (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\index.js:40:22)
    at runHookFunctions (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\simple-hooks-callback\lib\index.js:59:15)
    at afterRunHookFN (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\simple-hooks-callback\lib\index.js:66:7)
    at Object.recordField (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\title.js:28:7)
    at Object.titleMiddleware [as middleware] (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\title.js:10:72)
    at Array.runTitleMiddleware (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\index.js:35:20)
    at runHookFunctions (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\simple-hooks-callback\lib\index.js:59:15)
    at HooksPrototype.weTriggerEvent (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\simple-hooks-callback\lib\index.js:52:3)
    at Object.contextLoaded (C:\Users\sheab\Documents\scioly\Ezra\we-project-events-ezra2\node_modules\we-core\lib\Router\index.js:653:14)`

**Comment by albertosouza** [comment]
Thanks, i'll check

**Comment by albertosouza** [comment]
enableRequestLog should be added as one attr in your project config/local.js file.

`enableRequestLog: true`

**Comment by albertosouza** [comment]
The altFieldTimeOnly error may be version erros in we-core and we-plugin-form an update may solve this problem 

And for room session search bug try to use add manager search for search for someone like **admin** Url: http://localhost:4000/event/:eventId/admin/managers and see if it will return one user

**Comment by SHBelsky** [comment]
The only person who comes up is the default Administrator. I can also search for the Administrator when attempting to add a new event manager.

**Comment by albertosouza** [comment]
@SHBelsky you have others users created and active in you system right?

This search, search for users with query: displayName (contains), fullName (contains), email (equal)

**Comment by SHBelsky** [comment]
I haven't been able to register new users because of the bug I informed you of before. When trying to register a new user, I get this:

`ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'on' for column 'acceptTerms' at row 1`

Was that issue fixed? I haven't downloaded the newest versions yet, so I'm not sure.

**Comment by albertosouza** [comment]
Yes, i changed the default browser value to "true" that are changed to true (boolean) in We.js body parser

Please, update your project modules and test
For update you may use `npm update` , `npm-check-updates` or run the events generator in paren folder

**Comment by albertosouza** [comment]
But i think if user search is working and rooms search not may be permission configuration but ... i will check this ...

**Comment by albertosouza** [comment]
nvn, i did some tests and dont are permissions. i will need more information to replicate and fix this problem
